# Generated by Django 4.2.1 on 2023-05-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_parent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='update',
        ),
    ]
