# Generated by Django 4.2.1 on 2023-07-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
    ]
