# Generated by Django 4.2 on 2023-05-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_student_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
            ],
        ),
    ]
