# Generated by Django 4.2.1 on 2023-05-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_school'),
    ]

    operations = [
    ]
