# Generated by Django 4.2.1 on 2023-05-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230518_0443'),
    ]

    operations = [
    ]
