# Generated by Django 4.2.1 on 2023-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('E', '小学校'), ('J', '中学校'), ('H', '高校'), ('O', 'その他')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('O', 'その他')], max_length=10),
        ),
    ]
