# Generated by Django 4.2.1 on 2023-05-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_school_name_alter_student_gender'),
    ]

    operations = [
    ]
