# Generated by Django 4.2.1 on 2023-06-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_gradecoices_rename_adress_parent_address_school_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='classification',
            field=models.CharField(choices=[('E', '西東京市'), ('J', '東久留米市'), ('H', '新座市'), ('O', '練馬区'), ('P', '小平市')], max_length=10),
        ),
    ]
