# Generated by Django 4.2.1 on 2023-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_school_classification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeCoices',
        ),
        migrations.AddField(
            model_name='school',
            name='grade',
            field=models.CharField(blank=True, choices=[('e1', '小学1年性'), ('e2', '小学2年性'), ('e3', '小学3年性'), ('e4', '小学4年性'), ('e5', '小学5年性'), ('e6', '小学6年性'), ('j1', '中学1年性'), ('j2', '中学2年性'), ('j3', '中学3年性'), ('h1', '高校1年生'), ('h2', '高校2年生'), ('h3', '高校3年生')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='classification',
            field=models.CharField(choices=[('E', '小学校'), ('J', '中学校'), ('H', '高校'), ('O', 'その他')], max_length=10),
        ),
    ]
