# Generated by Django 4.2.1 on 2023-06-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_school_grade_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('T', '通塾'), ('C', '休塾'), ('R', '退塾')], max_length=10),
        ),
    ]
