# Generated by Django 4.2.1 on 2023-06-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('A', '通塾'), ('C', '休塾'), ('R', '退塾'), ('T', '体験')], max_length=10),
        ),
    ]
