# Generated by Django 4.2.1 on 2023-06-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_school_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='status',
            field=models.CharField(blank=True, choices=[('A', '通塾'), ('C', '休塾'), ('R', '退塾'), ('T', '体験')], max_length=10),
        ),
    ]
