# Generated by Django 4.2.1 on 2023-06-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_parent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='exam_01',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='exam_02',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='exam_03',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='exam_04',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='exam_05',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name_kana',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='status',
            field=models.CharField(blank=True, choices=[('通塾', '通塾'), ('休塾', '休塾'), ('退塾', '退塾'), ('体験', '体験')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, choices=[('西東京市', '西東京市'), ('東久留米市', '東久留米市'), ('新座市', '新座市'), ('練馬区', '練馬区'), ('小平市', '小平市')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('その他', 'その他')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('小学1年性', '小学1年性'), ('小学2年性', '小学2年性'), ('小学3年性', '小学3年性'), ('小学4年性', '小学4年性'), ('小学5年性', '小学5年性'), ('小学6年性', '小学6年性'), ('中学1年性', '中学1年性'), ('中学2年性', '中学2年性'), ('中学3年性', '中学3年性'), ('高校1年生', '高校1年生'), ('高校2年生', '高校2年生'), ('高校3年生', '高校3年生')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('通塾', '通塾'), ('休塾', '休塾'), ('退塾', '退塾'), ('体験', '体験')], max_length=10),
        ),
    ]
