# Generated by Django 4.2.1 on 2023-06-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_parent_how_to_know_parent_terms_student_course_and_more'),
    ]

    operations = [
    ]
