# Generated by Django 4.2 on 2023-06-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_parent_how_to_know_alter_student_introducer_and_more'),
    ]

    operations = [
    ]
