# Generated by Django 4.2 on 2023-06-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20230628_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name_kana',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name_kana',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_kana',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
