# Generated by Django 4.2.1 on 2023-06-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_name_kana_student_first_name_and_more'),
    ]

    operations = [
    ]
