# Generated by Django 4.2.1 on 2023-09-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('通塾', '通塾'), ('休塾', '休塾'), ('退塾', '退塾'), ('体験', '体験')], max_length=10)),
                ('terms', models.BooleanField(null=True)),
                ('how_to_know', models.CharField(blank=True, choices=[('webサイト', 'webサイト'), ('チラシ', 'チラシ'), ('紹介', '紹介'), ('兄弟が通塾している', '兄弟が通塾している'), ('知人からの紹介', '知人からの紹介'), ('看板を見た', '看板を見た'), ('その他', 'その他')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('小学校', '小学校'), ('中学校', '中学校'), ('高校', '高校'), ('その他', 'その他')], max_length=10)),
                ('city', models.CharField(blank=True, choices=[('西東京市', '西東京市'), ('東久留米市', '東久留米市'), ('新座市', '新座市'), ('練馬区', '練馬区'), ('小平市', '小平市')], max_length=10)),
                ('exam_01', models.DateField(blank=True, null=True)),
                ('exam_02', models.DateField(blank=True, null=True)),
                ('exam_03', models.DateField(blank=True, null=True)),
                ('exam_04', models.DateField(blank=True, null=True)),
                ('exam_05', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('last_name_kana', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('first_name_kana', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('その他', 'その他')], max_length=10)),
                ('sibling', models.BooleanField()),
                ('grade', models.CharField(blank=True, choices=[('小学1年生', '小学1年生'), ('小学2年生', '小学2年生'), ('小学3年生', '小学3年生'), ('小学4年生', '小学4年生'), ('小学5年生', '小学5年生'), ('小学6年生', '小学6年生'), ('中学1年生', '中学1年生'), ('中学2年生', '中学2年生'), ('中学3年生', '中学3年生'), ('高校1年生', '高校1年生'), ('高校2年生', '高校2年生'), ('高校3年生', '高校3年生')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('通塾', '通塾'), ('休塾', '休塾'), ('退塾', '退塾'), ('体験', '体験')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('introducer', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, choices=[('個別指導(月2回)', '個別指導(月2回)'), ('個別指導(月4回)', '個別指導(月4回)'), ('個別指導(月8回)', '個別指導(月8回)'), ('通い放題ベーシック', '通い放題ベーシック'), ('通い放題ライト', '通い放題ライト'), ('通い放題ミニ', '通い放題ミニ'), ('小学生本科', '小学生本科'), ('小学生総合', '小学生総合'), ('ロボット教室', 'ロボット教室'), ('プログラミング教室', 'プログラミング教室')], max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentMaster.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMaster.school')),
            ],
        ),
    ]
